version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
        user: root
        environment:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable
      - image: postgres:11.1
    working_directory: ~/fastapi-realworld-example-app
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: install python deps
          command: |
            pip install poetry
            poetry config settings.virtualenvs.create false
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: run migrations
          command: alembic upgrade head
      - run:
          name: start server and run postman tests
          command: |
            uvicorn app.main:app &
            APIURL=http://localhost:8000/api ./postman_tests/run-api-tests.sh

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install docker
          command: |
            VER="18.09.1"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: build image and push to registry
          command: |
            docker build -t $DOCKER_USER/fastapi-realworld-example-app .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOCKER_USER/fastapi-realworld-example-app
